### ISSUE TITLE
bug in "unused database settings" !

### ISSUE THREAD

**Issue by plyusninva** [gergo85/oc-backend-plus#23]
According to the condition in the line below, the "slick_slider_settings" setting in the database will be deleted, because the files in this plugin are stored in the "/plugins/peterhegman/slickslider/" folder, and not in the "/plugins/slick/slider/" as checked by you.
https://github.com/gergo85/oc-backend-plus/blob/1d3118fb288f8dbf4c58c56f01cf91edcb58e3d2/controllers/Trash.php#L39

Here is the link to the plugin https://octobercms.com/plugin/peterhegman-slickslider (https://github.com/phegman/October-CMS-Slick-Slider)

**Comment by gergo85** [comment]
Thank you for report this bug! I will fix it.

**Comment by gergo85** [comment]
I fixed this issue. Please update the plugin!

**Comment by plyusninva** [comment]
this does not solve the problem, there are hundreds of such plugins.

**Comment by gergo85** [comment]
I will find a better solution.

**Comment by gergo85** [comment]
I checked a lot of popular plugins. The most of them use the correct settings code, so I just added more exceptions for database search feature for now.
